"""add users and vacancy ownership

Revision ID: 96412cbc8440
Revises: bfb384d76552
Create Date: 2026-08-26 16:03:43.843898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96412cbc8440'
down_revision: Union[str, Sequence[str], None] = 'bfb384d76552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('vacancies', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_vacancies_owner_id'), 'vacancies', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'vacancies', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_index(op.f('ix_vacancies_owner_id'), table_name='vacancies')
    op.drop_column('vacancies', 'owner_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
